services:
  # Plataforma Anti Fraude (Frontend + ML Engine Local)
  fraud-detection:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    restart: always
    command: streamlit run src/frontend.py --server.port 8501 --server.address 0.0.0.0

